name: fir-cli
properties:
  - name: FIR_TOKEN
    type: string
    required: true

  - name: FIR_APP_PATH
    type: string
    required: false

run: |
  workpath=`pwd`
  mkdir -p /tmp/fir-cli
  cp -R $workpath/* /tmp/fir-cli/
  cd /tmp/fir-cli
  bundle install
  fir publish ${FIR_APP_PATH} --token=$FIR_TOKEN
  rm -rf /tmp/fir-cli
