name: fir-cli
properties:
  - name: FIR_TOKEN
    type: string
    required: true

  - name: FIR_APP_PATH
    type: string
    required: false

run: |
  gem build fir-cli.gemspec
  gem install *.gem
  fir publish ${FIR_APP_PATH} --token=$FIR_TOKEN