rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2
  - jruby
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-2
notifications:
  recipients:
    - hxy@fir.im
branches:
  only:
    - master
env:
  - ARTIFACTS_KEY=(AKIAOCMZ67QT4IJBQUMQ)
  - ARTIFACTS_SECRET=(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)
  - ARTIFACTS_BUCKET=(flow-file)
addons:
  code_climate:
    repo_token: 7158bd5d0218441524b8663790dd28edba8a870387ed000a1b56968e3315af2a
  artifacts:
    artifacts: true
    paths:
    - $(git ls-files -o | tr "\n" ":")
    - $(ls /var/log/*.log | tr "\n" ":")
    - $HOME/some/other/thing.log